### ISSUE TITLE
fix balance transfers on account page

### ISSUE THREAD

**Issue by hitchhooker** [polkadot-cloud/polkadot-developer-console#171]
account page tx field doesnt allow floats, and seems to overflow if inserting over 32bit digit values
![image](https://github.com/user-attachments/assets/5b717ec9-09fe-49f5-b19a-4c8f8b4bc3c1)

**Comment by rossbulat** [comment]
I just deployed an update, please let me know if the issue persists for you.

**Comment by hitchhooker** [comment]
lgtm
